
- alias: Lights on when PS4 turned off
  trigger:
    platform: state
    entity_id: switch.playstation4
    to: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.room
      brightness: 255

- alias: Good Morning
  trigger:
    platform: time
    # When 'after' is used, you cannot also match on hour, minute, seconds.
    # Military time format.
    after: '08:05:00'
  action:
    service: tts.google_say
    entity_id: media_player.bedroom_home
    data:
      message: 'Good Morning. Time to rise and shine bitches'


# - alias: Flash Lights when ps4 turned OFF
#   trigger:
#     platform: state
#     entity_id: switch.playstation4
#     to: 'off'
#   action:
#     service: script.turn_on
#     entity_id: script.flash_lights

# - alias: PS4 Open Netflix
#   hide_entity: true
#   trigger:
#    platform: state
#    entity_id: 'input_select.playstation4app' 
#    to: "Netflix"  
#   action:
#     - service: shell_command.playstation_netflix_start
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.playstation4app
#         option: "-- Select an App --"
#     - service: notify.notifyall
#       data:
#         message: "Playstation starting netflix"

- alias: PS4 Open Netflix
  trigger:
   platform: state
   entity_id: 'input_select.playstation4app' 
   to: "Netflix"  
  action:
    - service: shell_command.playstation_netflix_start
    - service: input_select.select_option
      data:
        entity_id: input_select.playstation4app
        option: "-- Select an App --"
    - service: light.turn_on
      data:
        entity_id: light.room
        brightness: 20

- alias: PS4 Open Hulu
  trigger:
   platform: state
   entity_id: 'input_select.playstation4app' 
   to: "Hulu"  
  action:
    - service: shell_command.playstation_hulu_start
    - service: input_select.select_option
      data:
        entity_id: input_select.playstation4app
        option: "-- Select an App --"
    - service: notify.notifyall
      data:
        message: "Playstation starting Hulu"

- alias: PS4 Open OverWatch
  trigger:
   platform: state
   entity_id: 'input_select.playstation4app' 
   to: "OverWatch"  
  action:
    - service: shell_command.playstation_overwatch_start
    - service: input_select.select_option
      data:
        entity_id: input_select.playstation4app
        option: "-- Select an App --"
    - service: notify.notifyall
      data:
        message: "Playstation starting OverWatch"


- alias: PS4 Open GTA V
  trigger:
   platform: state
   entity_id: 'input_select.playstation4app' 
   to: "GTA V"  
  action:
    - service: shell_command.playstation_gtav_start
    - service: input_select.select_option
      data:
        entity_id: input_select.playstation4app
        option: "-- Select an App --"
    - service: notify.notifyall
      data:
        message: "Playstation starting GTA V"


# Fan Brightness from slider
- alias: Fan Light - Adjust Brightness
  trigger:
    platform: state
    entity_id: input_slider.fan_brightness
  action:
    - service: light.turn_on
  # Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
      data_template:
        entity_id: light.hue_white_lamp_1
        brightness: '{{ states.input_slider.fan_brightness.state | int }}'

# Fan Brightness from its set state
- alias: Fan Light - From state
  trigger:
    platform: state
    entity_id: ligt.hue_white_lamp_1
  action:
    - service: input_slider.select_value
      data:
        brightness: '{{ states.light.hue_white_lamp_1.attributes.brightness | int }}'

# Lamp Brightness from Slider
- alias: Lamp Light - Adjust Brightness
  trigger:
    platform: state
    entity_id: input_slider.lamp_brightness
  action:
    - service: light.turn_on
    # Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
      data_template:
        entity_id: light.hue_white_lamp_2
        brightness: '{{ states.input_slider.lamp_brightness.state | int }}'

# Light Slider from lamp state
- alias: Lamp Slider - From state
  trigger:
    platform: state
    entity_id: ligt.hue_white_lamp_1
  action:
    - service: input_slider.select_value
      data:
        brightness: '{{ states.light.hue_white_lamp_1.attributes.brightness | int }}'






