
- platform: imap
  server: imap.gmail.com
  port: 993
  username: !secret imap_username
  password: thisismofogoogle
# lastfm
- platform: lastfm
  api_key: !secret lastfm_api_key
  users:
    - !secret lastfm_user

# speedtest
- platform: speedtest
  monitored_conditions:
    # - ping
    - download
    # - upload

#System Monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use

# Weather Prediction
- platform: yr

# # WEB SCRAPING
# - platform: scrape
#   resource: https://news.ycombinator.com/
#   select: "tbody"

# - platform: command_line
#   command: orders
#   name: Order Status
#   scan_interval: 30000
